// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7ikoNv5vJxqcX4JjitqX90etF_-oHRdA',
    appId: '1:829607849782:web:c7392557b77aed23d58d97',
    messagingSenderId: '829607849782',
    projectId: 'appotp-aa75e',
    authDomain: 'appotp-aa75e.firebaseapp.com',
    storageBucket: 'appotp-aa75e.appspot.com',
    measurementId: 'G-5C8XS6963L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA67ePdkixGnBO_8031j7dSqPOzUGCtYS4',
    appId: '1:829607849782:android:c4303637644ab029d58d97',
    messagingSenderId: '829607849782',
    projectId: 'appotp-aa75e',
    storageBucket: 'appotp-aa75e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHQx6mlGKHyAVpJVPVSz6hbs7d6dcKwSM',
    appId: '1:829607849782:ios:652a51e21f1b169fd58d97',
    messagingSenderId: '829607849782',
    projectId: 'appotp-aa75e',
    storageBucket: 'appotp-aa75e.appspot.com',
    iosBundleId: 'com.example.flutterotp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHQx6mlGKHyAVpJVPVSz6hbs7d6dcKwSM',
    appId: '1:829607849782:ios:652a51e21f1b169fd58d97',
    messagingSenderId: '829607849782',
    projectId: 'appotp-aa75e',
    storageBucket: 'appotp-aa75e.appspot.com',
    iosBundleId: 'com.example.flutterotp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7ikoNv5vJxqcX4JjitqX90etF_-oHRdA',
    appId: '1:829607849782:web:7d08ee6c116f8c20d58d97',
    messagingSenderId: '829607849782',
    projectId: 'appotp-aa75e',
    authDomain: 'appotp-aa75e.firebaseapp.com',
    storageBucket: 'appotp-aa75e.appspot.com',
    measurementId: 'G-CDDCZMYTK7',
  );
}
